# Generated by Django 5.0.6 on 2024-08-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0002_alter_site_options_alter_site_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "facebook_url",
                    models.URLField(blank=True, help_text="URL of the Facebook page for this site.", null=True),
                ),
                (
                    "twitter_username",
                    models.CharField(blank=True, help_text="Twitter username without the @ symbol.", max_length=50),
                ),
                (
                    "support_email",
                    models.EmailField(
                        blank=True, help_text="Email address for support requests.", max_length=254, null=True
                    ),
                ),
                (
                    "newsletter_signup_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for a basic ewsletter signup form, ostensibly on a third-party email automation provider.",
                        null=True,
                    ),
                ),
                (
                    "educators_newsletter_signup_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for an educators newsletter signup form, ostensibly on a third-party email automation provider.",
                        null=True,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="profile", to="sites.site"
                    ),
                ),
            ],
        ),
    ]
