# Generated by Django 5.0.6 on 2024-09-05 01:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, help_text="A unique identifier for this site. This should be a UUID.", null=True
            ),
        ),
    ]
