# Generated by Django 5.0.6 on 2024-09-05 01:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_siteprofile_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, help_text="A unique uuid identifier for this site.", null=True),
        ),
    ]
