# Generated by Django 5.1.1 on 2024-09-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_siteprofile_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="description",
            field=models.TextField(blank=True, help_text="A short description of the site.", null=True),
        ),
    ]
