# Generated by Django 5.0.9 on 2024-11-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_siteprofile_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="institution_name",
            field=models.CharField(
                blank=True, help_text="The name of the institution or organization.", max_length=500
            ),
        ),
    ]
