# Generated by Django 5.0.6 on 2024-08-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("sites", "0002_alter_site_options_alter_site_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumTopic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "topic_id",
                    models.IntegerField(blank=True, help_text="ID of category in external forum service", null=True),
                ),
                (
                    "topic_slug",
                    models.SlugField(
                        blank=True, help_text="Slug of category in external forum service", max_length=200, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CohortForumGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_default", models.BooleanField(default=True)),
                ("group_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "course",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohort_forum_groups",
                        to="course.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseForumGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group_id", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                (
                    "course",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_forum_group",
                        to="course.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForumCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category_id", models.IntegerField(blank=True, null=True)),
                ("category_slug", models.SlugField(blank=True, null=True)),
                (
                    "course",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forum_category",
                        to="course.course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Forum categories",
            },
        ),
        migrations.CreateModel(
            name="ForumProvider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[("DISCOURSE", "Discourse")],
                        default="DISCOURSE",
                        help_text="Type of forum utilized for this site.",
                        max_length=30,
                    ),
                ),
                (
                    "forum_url",
                    models.URLField(
                        blank=True, help_text="URL of the forum server for this site, if available.", null=True
                    ),
                ),
                ("active", models.BooleanField(default=False, help_text="Enable forums for this site.")),
                (
                    "forum_api_username",
                    models.CharField(
                        blank=True,
                        help_text="API username for the forum server for this site, if available.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "enable_sso",
                    models.BooleanField(default=True, help_text="Enable SSO for this external forum server"),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="forum_provider", to="sites.site"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForumSubcategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("COHORT", "cohort"), ("ALL_ENROLLED", "all_enrolled")],
                        default=None,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "subcategory_id",
                    models.IntegerField(
                        blank=True, help_text="ID of subcategory in external forum service", null=True
                    ),
                ),
                (
                    "subcategory_slug",
                    models.SlugField(blank=True, help_text="Slug of subcategory in external forum service", null=True),
                ),
                (
                    "cohort_forum_group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forum_cohort_subcategory",
                        to="forum.cohortforumgroup",
                    ),
                ),
                (
                    "course_forum_group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forum_course_subcategory",
                        to="forum.courseforumgroup",
                    ),
                ),
                (
                    "forum_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_subcategories",
                        to="forum.forumcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Forum subcategories",
            },
        ),
    ]
