# Generated by Django 5.0.6 on 2024-08-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("forum", "0001_initial"),
        ("learning_library", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumtopic",
            name="block",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forum_topics",
                to="learning_library.block",
            ),
        ),
        migrations.AddField(
            model_name="forumtopic",
            name="forum_subcategory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forum_topics",
                to="forum.forumsubcategory",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="forumtopic",
            unique_together={("block", "forum_subcategory")},
        ),
    ]
