# Generated by Django 5.0.6 on 2024-08-05 10:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenericResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("resource_type", models.CharField(choices=[("PDF", "pdf")], max_length=30)),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
