services:
  redis:
    image: redis:6.2.7-alpine
    ports:
      - '${DC_REDIS_PORT-6379}:6379'
    volumes:
      - redis:/data

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '${DC_DB_PORT-5432}:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  redis:
    driver: local
  db:
    driver: local
