# Generated by Django 5.0.6 on 2024-08-05 10:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "custom_template_name",
                    models.CharField(
                        blank=True,
                        help_text="Custom template name to use for certificate (if any). This template should exist in templates/course/certificate/custom",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="An admin description of this certificate template.",
                        max_length=200,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Signatory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("organization", models.CharField(max_length=200)),
                ("signature_image", models.FileField(upload_to="signatures/")),
            ],
        ),
    ]
