# Generated by Django 5.0.6 on 2024-08-05 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("certificates", "0001_initial"),
        ("course", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="certificates", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="course",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="certificate_template", to="course.course"
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="certificate_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="certificates.certificatetemplate"
            ),
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="signatories",
            field=models.ManyToManyField(
                blank=True, related_name="certificate_templates", to="certificates.signatory"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="certificate",
            unique_together={("student", "certificate_template")},
        ),
    ]
