# Generated by Django 5.0.6 on 2024-08-05 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=250, unique=True)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("featured_image", models.FileField(blank=True, null=True, upload_to="")),
                ("content", models.TextField()),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("published_on", models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ("status", models.IntegerField(choices=[(0, "Draft"), (1, "Publish")], default=0)),
                ("featured_image_credit", models.CharField(blank=True, max_length=200, null=True)),
                ("featured_image_alt", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "ordering": ["-published_on"],
            },
        ),
    ]
