# Generated by Django 5.0.6 on 2024-08-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseCatalogDescription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="The title of the course to be shown in the catalog.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "blurb",
                    models.CharField(
                        blank=True,
                        help_text="A short, marketing-oriented description of the course. Only one or two sentences long.",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "overview",
                    models.TextField(
                        blank=True,
                        help_text="A short description of the course, usually just a paragraph long.",
                        null=True,
                    ),
                ),
                (
                    "about_content",
                    models.TextField(
                        blank=True,
                        help_text="The long, detailed content shown on the course about page. HTML is okay.",
                        null=True,
                    ),
                ),
                (
                    "sidebar_content",
                    models.TextField(
                        blank=True,
                        help_text="Other information to show in the sidebar, if present. HTML is okay.",
                        null=True,
                    ),
                ),
                (
                    "thumbnail",
                    models.FileField(
                        blank=True,
                        help_text="The image to be used in the catalog card. If empty, KinesinLMS will show the 'catalog/static/catalog/default_course_thumbnail.jpg' image.",
                        null=True,
                        upload_to="catalog/images/",
                    ),
                ),
                ("visible", models.BooleanField(default=True, help_text="Show this course in the course catalog")),
                (
                    "hex_theme_color",
                    models.CharField(
                        default="e1e1e1",
                        help_text="The hex value for the 'theme' color. This color is used, e.g. as the background of the hero bar on the course about page.",
                        max_length=6,
                    ),
                ),
                (
                    "hex_title_color",
                    models.CharField(
                        default="ffffff",
                        help_text="The hex value for the color of the title text on the about page",
                        max_length=6,
                    ),
                ),
                (
                    "custom_stylesheet",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="The filename of the custom css stylesheet to use when showing course content.",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "trailer_video_url",
                    models.URLField(blank=True, help_text="URL for the trailer video", max_length=250, null=True),
                ),
                (
                    "syllabus",
                    models.FileField(
                        blank=True,
                        help_text="The public syllabus for the course, shown to users who are considering enrolling.",
                        null=True,
                        upload_to="catalog/syllabi/",
                    ),
                ),
                (
                    "effort",
                    models.CharField(
                        blank=True,
                        help_text="Generic text description of effort, e.g. '3 hours / week'",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("num_modules", models.IntegerField(blank=True, null=True)),
                ("duration", models.CharField(blank=True, max_length=100, null=True)),
                ("audience", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "features",
                    models.JSONField(
                        blank=True, help_text="An array of strings describing each feature of the course.", null=True
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Used for ordering cards in the course catalog")),
            ],
            options={
                "ordering": ("order",),
            },
        ),
    ]
