# Generated by Django 5.0.9 on 2024-12-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecatalogdescription",
            name="blurb",
            field=models.CharField(blank=True, help_text="A short, marketing-oriented description of the course. Only one or two sentences long.", max_length=500, null=True),
        ),
    ]
