# Generated by Django 5.0.6 on 2024-08-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(blank=True, default="1", max_length=200, null=True)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("anon_username", models.UUIDField(blank=True, null=True)),
                ("course_slug", models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True)),
                ("course_run", models.CharField(blank=True, max_length=200, null=True)),
                ("unit_node_slug", models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True)),
                ("course_unit_id", models.IntegerField(blank=True, null=True)),
                ("course_unit_slug", models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True)),
                ("block_uuid", models.UUIDField(blank=True, null=True)),
                ("event_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-time",),
            },
        ),
    ]
