# Generated by Django 5.1.1 on 2024-10-07 03:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("event_type", models.CharField(blank=True, default="1", max_length=200, null=True)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("anon_username", models.UUIDField(blank=True, null=True)),
                ("course_slug", models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True)),
                ("course_run", models.CharField(blank=True, max_length=200, null=True)),
                ("unit_node_slug", models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True)),
                ("course_unit_id", models.IntegerField(blank=True, null=True)),
                ("course_unit_slug", models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True)),
                ("block_uuid", models.UUIDField(blank=True, null=True)),
                ("event_data", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracking_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-time",),
                "indexes": [
                    models.Index(fields=["time"], name="tracking_tr_time_345c19_idx"),
                    models.Index(fields=["event_type"], name="tracking_tr_event_t_f7f135_idx"),
                ],
            },
        ),
    ]
