# Generated by Django 5.0.6 on 2024-08-05 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tracking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trackingevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracking_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="trackingevent",
            index=models.Index(fields=["time"], name="tracking_tr_time_345c19_idx"),
        ),
        migrations.AddIndex(
            model_name="trackingevent",
            index=models.Index(fields=["event_type"], name="tracking_tr_event_t_f7f135_idx"),
        ),
    ]
