# Generated by Django 5.0.9 on 2024-11-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_library", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="type",
            field=models.CharField(
                choices=[
                    ("VIDEO", "Video"),
                    ("HTML_CONTENT", "HTML Content"),
                    ("FILE_RESOURCE", "File Resource"),
                    ("CALLOUT", "Callout"),
                    ("ANSWER_LIST", "Answer List"),
                    ("ASSESSMENT", "Assessment"),
                    ("FORUM_TOPIC", "Forum Topic"),
                    ("SIMPLE_INTERACTIVE_TOOL", "Simple interactive tool"),
                    ("SURVEY", "Survey"),
                    ("JUPYTER_NOTEBOOK", "Jupyter Notebook"),
                    ("EXTERNAL_TOOL_VIEW", "External tool view"),
                ],
                default="HTML_CONTENT",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="type",
            field=models.CharField(
                choices=[
                    ("GENERIC", "Generic"),
                    ("IMAGE", "Image"),
                    ("VIDEO_TRANSCRIPT", "Video transcript"),
                    ("JUPYTER_NOTEBOOK", "Jupyter Notebook"),
                ],
                default="IMAGE",
                max_length=50,
            ),
        ),
    ]
