# Generated by Django 5.0.9 on 2024-11-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_library", "0002_alter_block_type_alter_resource_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="A name for this resource. This name is used in the admin interface and in the learning library.",
                max_length=400,
                null=True,
            ),
        ),
    ]
