# Generated by Django 5.0.9 on 2024-11-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_library", "0004_alter_block_type_alter_resource_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="type",
            field=models.CharField(
                choices=[
                    ("VIDEO", "Video"),
                    ("HTML_CONTENT", "HTML Content"),
                    ("FILE_RESOURCE", "File Resource"),
                    ("CALLOUT", "Callout"),
                    ("ANSWER_LIST", "Answer List"),
                    ("ASSESSMENT", "Assessment"),
                    ("FORUM_TOPIC", "Forum Topic"),
                    ("SIMPLE_INTERACTIVE_TOOL", "Simple interactive tool"),
                    ("SURVEY", "Survey"),
                    ("JUPYTER_LAB", "JupyterLab"),
                    ("EXTERNAL_TOOL_VIEW", "External tool view"),
                ],
                default="HTML_CONTENT",
                max_length=50,
            ),
        ),
    ]
