# Generated by Django 5.0.9 on 2024-11-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_library", "0005_alter_block_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="type",
            field=models.CharField(
                choices=[
                    ("GENERIC", "Generic"),
                    ("IMAGE", "Image"),
                    ("VIDEO_TRANSCRIPT", "Video transcript"),
                    ("JUPYTER_NOTEBOOK", "Jupyter Notebook"),
                ],
                default="IMAGE",
                max_length=50,
            ),
        ),
    ]
