# Generated by Django 5.0.9 on 2024-11-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_library", "0006_alter_resource_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="type",
            field=models.CharField(
                choices=[
                    ("GENERIC", "Generic"),
                    ("IMAGE", "Image"),
                    ("VIDEO_TRANSCRIPT", "Video transcript"),
                    ("JUPYTER_NOTEBOOK", "Jupyter Notebook"),
                    ("SQLITE", "SQLITE file"),
                    ("CSV", "CSV file"),
                ],
                default="IMAGE",
                max_length=50,
            ),
        ),
    ]
