# Generated by Django 5.0.9 on 2024-11-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_library", "0010_populate_resource_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                help_text="A slug for this resource. The main use of a slug here is simple indication of purpose of resource, both for students (when seen in a URL for this resource if its available in the learning library) and for admins (when viewing event data in event objects).",
                max_length=300,
                unique=True,
            ),
        ),
    ]
