# Generated by Django 5.0.9 on 2024-12-02 00:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_library", "0012_alter_resource_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitblock",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
