# Generated by Django 5.0.6 on 2024-08-05 10:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProgressReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "task_result",
                    models.CharField(
                        choices=[
                            ("UNGENERATED", "Ungenerated"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default="UNGENERATED",
                        max_length=50,
                    ),
                ),
                ("generation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "percent_complete",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("task_message", models.TextField(blank=True, null=True)),
                ("modules_info_json", models.JSONField(blank=True, null=True)),
                ("students_modules_progresses_json", models.JSONField(blank=True, null=True)),
                ("num_students", models.IntegerField(default=0)),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress_reports",
                        to="course.cohort",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress_reports",
                        to="course.course",
                    ),
                ),
            ],
            options={
                "get_latest_by": "updated_at",
            },
        ),
    ]
