# Generated by Django 5.0.6 on 2024-08-05 10:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("sites", "0002_alter_site_options_alter_site_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseEmailAutomationSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "active",
                    models.BooleanField(default=True, help_text="Enable email automation service for this course."),
                ),
                (
                    "send_event_as_tag",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("USER_REGISTRATION", "kinesinlms.core.user.registration"),
                                ("ENROLLMENT_ACTIVATED", "kinesinlms.core.user.enrollment.activated"),
                                ("ENROLLMENT_DEACTIVATED", "kinesinlms.core.user.enrollment.deactivated"),
                                ("COURSE_CERTIFICATE_EARNED", "kinesinlms.course.progress.certificate.earned"),
                            ],
                            help_text="Tracking events that will be sent as a tag to email automation.",
                            max_length=50,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_automation_settings",
                        to="course.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailAutomationProvider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[("ACTIVE_CAMPAIGN", "ActiveCampaign")],
                        help_text="Provider of email automation provider.",
                        max_length=30,
                    ),
                ),
                ("active", models.BooleanField(default=True, help_text="Enable email automation provider.")),
                ("api_url", models.URLField(help_text="Email automation provider API endpoint")),
                (
                    "tag_ids",
                    models.JSONField(
                        blank=True,
                        help_text="If a provider supports tags, but uses IDs rather than the the tag itself during API calls, this field maps tag names to the tag IDs.",
                        null=True,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_automation_provider",
                        to="sites.site",
                    ),
                ),
            ],
        ),
    ]
