# Generated by Django 5.0.6 on 2024-08-05 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("badges", "0001_initial"),
        ("course", "0001_initial"),
        ("sites", "0002_alter_site_options_alter_site_domain"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="badgeassertion",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badge_assertions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="badgeclass",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badge_classes",
                to="course.course",
            ),
        ),
        migrations.AddField(
            model_name="badgeassertion",
            name="badge_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="badge_assertions", to="badges.badgeclass"
            ),
        ),
        migrations.AddField(
            model_name="badgeprovider",
            name="site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="badge_provider", to="sites.site"
            ),
        ),
        migrations.AddField(
            model_name="badgeclass",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="providers",
                to="badges.badgeprovider",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="badgeclass",
            unique_together={("course", "slug")},
        ),
    ]
