# Generated by Django 5.0.6 on 2024-08-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducatorSurvey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("plan_to_use", models.TextField(blank=True, null=True)),
                (
                    "evaluating",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Yes"), ("NO", "No"), ("NOT_SURE", "Not sure")],
                        max_length=40,
                        null=True,
                    ),
                ),
                ("institution", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EducatorResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("GUIDE", "guide"),
                            ("DOCUMENT", "document"),
                            ("VIDEO", "video"),
                            ("AUDIO", "audio"),
                            ("OTHER", "other"),
                        ],
                        default="GUIDE",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "overview",
                    models.TextField(blank=True, help_text="A short description of the educator resource.", null=True),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="The complete content of the resource (if it's just text and you want to store it here.)",
                        null=True,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="educator_resources/files/")),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="URL to resource, if the resource is hosted externally.", null=True
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educator_resources",
                        to="course.course",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
