# Generated by Django 5.0.6 on 2024-08-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("learning_library", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pathway",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(blank=True, default=None, max_length=250, null=True)),
                ("description", models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PathStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "learning_object",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning_library.block"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
