# Generated by Django 5.0.6 on 2024-08-05 10:04

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("learning_library", "0001_initial"),
        ("pathways", "0001_initial"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pathway",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="pathways", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="pathway",
            name="learning_objects",
            field=models.ManyToManyField(
                related_name="path_steps", through="pathways.PathStep", to="learning_library.block"
            ),
        ),
        migrations.AddField(
            model_name="pathway",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="pathstep",
            name="pathway",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pathways.pathway"),
        ),
    ]
