# Generated by Django 5.0.9 on 2024-12-09 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_alter_course_tags_alter_courseunit_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="course_home_content",
            new_name="course_home_html_content",
        ),
    ]
