# Generated by Django 5.0.6 on 2024-08-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("learning_library", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseSpeaker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "has_course_headshot",
                    models.BooleanField(
                        default=False, help_text="Use a course-specific headshot (rather than the default headshot)"
                    ),
                ),
                (
                    "has_course_video",
                    models.BooleanField(
                        default=False, help_text="Use a course-specific bio video (rather than the default bio video)"
                    ),
                ),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="course.course")),
            ],
        ),
        migrations.CreateModel(
            name="Speaker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(blank=True, max_length=200, null=True)),
                ("last_name", models.CharField(blank=True, max_length=200, null=True)),
                ("full_name", models.CharField(blank=True, max_length=200, null=True)),
                ("video_url", models.CharField(blank=True, max_length=200, null=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("suffix", models.CharField(blank=True, max_length=50, null=True)),
                ("title", models.CharField(blank=True, max_length=400, null=True)),
                ("institution", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pronouns", models.CharField(blank=True, max_length=200, null=True)),
                ("identities", models.CharField(blank=True, max_length=400, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("blocks", models.ManyToManyField(blank=True, related_name="speakers", to="learning_library.block")),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True, related_name="speakers", through="speakers.CourseSpeaker", to="course.course"
                    ),
                ),
            ],
            options={
                "ordering": ["last_name"],
            },
        ),
        migrations.AddField(
            model_name="coursespeaker",
            name="speaker",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="speakers.speaker"),
        ),
    ]
