# Generated by Django 5.0.9 on 2024-12-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("speakers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="headshot_image",
            field=models.ImageField(blank=True, null=True, upload_to="speakers"),
        ),
    ]
