data = {
    "topic": {
        "id": 598,
        "title": "P-Values: a topic for discussion",
        "fancy_title": "P-Values: a topic for discussion",
        "posts_count": 1,
        "created_at": "2020-09-07T22:41:14.559Z",
        "views": 0,
        "reply_count": 0,
        "like_count": 0,
        "last_posted_at": "2020-09-07T22:41:14.619Z",
        "visible": True,
        "closed": False,
        "archived": False,
        "archetype": "regular",
        "slug": "p-values-a-topic-for-discussion",
        "category_id": 227,
        "word_count": 85,
        "deleted_at": None,
        "user_id": 2,
        "featured_link": None,
        "pinned_globally": False,
        "pinned_at": None,
        "pinned_until": None,
        "unpinned": None,
        "pinned": False,
        "highest_post_number": 1,
        "deleted_by": None,
        "has_deleted": False,
        "bookmarked": False,
        "participant_count": 1,
        "thumbnails": None,
        "created_by": {
            "id": 2,
            "username": "daniel",
            "name": "None",
            "avatar_template": "/user_avatar/discuss.kinesinlms.org/daniel/{size}/2_2.png"
        },
        "last_poster": {
            "id": 2,
            "username": "daniel",
            "name": "None",
            "avatar_template": "/user_avatar/discuss.kinesinlms.org/daniel/{size}/2_2.png"
        },
        "tags_disable_ads": False
    }
}

# When I create a topic, this event arrives in the webhook handler...

event_data = {
    "id": 641,
    "name": "None",
    "username": "daniel",
    "avatar_template": "/user_avatar/discuss.kinesinlms.org/daniel/{size}/2_2.png",
    "created_at": "2020-09-07T22:41:14.619Z",
    "cooked": "<p>Please respond to the ...",
    "post_number": 1,
    "post_type": 1,
    "updated_at": "2020-09-07T22:41:14.619Z",
    "reply_count": 0,
    "reply_to_post_number": None,
    "quote_count": 0,
    "incoming_link_count": 0,
    "reads": 0,
    "score": 0,
    "topic_id": 598,
    "topic_slug": "p-values-a-topic-for-discussion",
    "topic_title": "P-Values: a topic for discussion",
    "category_id": 227,
    "display_username": "None",
    "primary_group_name": "SYR_SP",
    "version": 1,
    "user_title": "",
    "bookmarked": False,
    "raw": "<p>Please respond to the questions ...",
    "moderator": False,
    "admin": True,
    "staff": True,
    "user_id": 2,
    "hidden": False,
    "trust_level": 1,
    "deleted_at": None,
    "user_deleted": False,
    "edit_reason": None,
    "wiki": False,
    "reviewable_id": None,
    "reviewable_score_count": 0,
    "reviewable_score_pending_count": 0,
    "topic_posts_count": 1,
    "topic_filtered_posts_count": 1,
    "topic_archetype": "regular",
    "category_slug": "topics-co-DEFAULT"
}
