# Generated by Django 5.0.6 on 2024-08-05 10:04

import kinesinlms.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalToolProvider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Name of external tool.", max_length=200, unique=True)),
                ("description", models.TextField(blank=True, help_text="Description of external tool.", null=True)),
                ("lti_version", models.CharField(choices=[("LTI_1_3", "LTI 1.3")], default="LTI_1_3", max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("BASIC", "Basic"), ("JUPYTER_HUB", "Jupyterhub")],
                        default="JUPYTER_HUB",
                        max_length=50,
                    ),
                ),
                (
                    "connection_method",
                    models.CharField(choices=[("MANUAL", "manual")], default="MANUAL", max_length=50),
                ),
                (
                    "username_field",
                    models.CharField(
                        choices=[
                            ("USERNAME", "username"),
                            ("EMAIL", "email"),
                            ("ANON_USERNAME", "anonymous username"),
                        ],
                        default="USERNAME",
                        help_text="The field in the user model that will be used to identify the user to the tool",
                        max_length=50,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug identifier for provider (used in e.g. course json imports).",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("launch_uri", models.URLField(help_text="The launch (target link) URI for this external tool.")),
                (
                    "login_url",
                    models.URLField(
                        blank=True,
                        help_text="The login URL that starts the OpenID Connect process for this external tool. This field can be left empty if not required by external tool.",
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=False, help_text="Enable external tool provider.")),
                (
                    "public_keyset_url",
                    models.URLField(
                        blank=True,
                        help_text="The public keyset URL for the external tool. The public key for the external tool. (Only needed if you want to support LTI Advantage.)",
                        null=True,
                    ),
                ),
                (
                    "public_key",
                    models.TextField(
                        blank=True,
                        help_text="The public key for the external tool. (Only needed if you want to support LTI Advantage.)",
                        null=True,
                    ),
                ),
                (
                    "client_id",
                    models.SlugField(
                        blank=True,
                        help_text="The opaque client ID that represents the tool in KinesinLMS. This will be provided to the tool as part of the LTI configuration.",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExternalToolView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "launch_type",
                    models.CharField(
                        choices=[
                            ("BLANK", "Blank window"),
                            ("MODAL", "Modal window"),
                            ("IFRAME", "iframe"),
                            ("STUDENT_CHOICE", "student's choice"),
                        ],
                        default="IFRAME",
                        max_length=50,
                    ),
                ),
                (
                    "resource_link_id",
                    kinesinlms.core.fields.AutoCharField(
                        help_text="A unique identifier for this external tool view.", max_length=36, unique=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
