# Generated by Django 5.0.6 on 2024-08-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("external_tools", "0001_initial"),
        ("learning_library", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaltoolview",
            name="block",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_tool_view",
                to="learning_library.block",
            ),
        ),
        migrations.AddField(
            model_name="externaltoolview",
            name="external_tool_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_tool_views",
                to="external_tools.externaltoolprovider",
            ),
        ),
    ]
