# Generated by Django 5.0.9 on 2024-10-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_tools", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaltoolprovider",
            name="default_target_link_uri",
            field=models.CharField(
                blank=True,
                help_text="The default target_link_uri sent as part of the tool launch. This value can be left empty. This value can also be overridden in Composer when a tool is added to a course unit.",
                max_length=1000,
                null=True,
                verbose_name="Default Target Link URI",
            ),
        ),
        migrations.AddField(
            model_name="externaltoolview",
            name="custom_target_link_uri",
            field=models.CharField(
                blank=True,
                help_text="A custom target link helps direct to a particular resources in the external tool. If this URL is not defined, the default launch URI of the ExternalToolProvider will be used to launch the tool.",
                max_length=1000,
                null=True,
                verbose_name="Custom Target Link URI",
            ),
        ),
        migrations.AlterField(
            model_name="externaltoolprovider",
            name="launch_uri",
            field=models.URLField(
                help_text="The launch (target link) URI for this external tool.This is the URL to launch the tool once the login process is complete.Sometimes this URL is called the 'redirection URI'."
            ),
        ),
        migrations.AlterField(
            model_name="externaltoolprovider",
            name="login_url",
            field=models.URLField(
                blank=True,
                help_text="The login URL that starts the OpenID Connect process for this external tool. Sometimes this URL is called the 'initiate login', the 'OIDC url' or just 'login' url. This field can be left empty if not required by external tool.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="externaltoolview",
            name="launch_type",
            field=models.CharField(
                choices=[("WINDOW", "window"), ("IFRAME", "iframe")], default="IFRAME", max_length=50
            ),
        ),
    ]
