# Generated by Django 5.0.6 on 2024-08-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_tools", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaltoolprovider",
            name="launch_uri",
            field=models.URLField(
                help_text="The launch (target link) URI for this external tool.This is the URL to launch the tool once the login process is complete.Sometimes this URL is called the 'redirection URI'."
            ),
        ),
        migrations.AlterField(
            model_name="externaltoolprovider",
            name="login_url",
            field=models.URLField(
                blank=True,
                help_text="The login URL that starts the OpenID Connect process for this external tool. Sometimes this URL is called the 'initiate login', the 'OIDC url' or just 'login' url. This field can be left empty if not required by external tool.",
                null=True,
            ),
        ),
    ]
