# Generated by Django 5.0.9 on 2024-10-16 23:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("external_tools", "0003_externaltoolprovider_default_target_link_uri_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externaltoolprovider",
            name="default_target_link_uri",
        ),
    ]
