# Generated by Django 5.0.9 on 2024-10-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_tools", "0003_externaltoolview_custom_target_link_uri_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externaltoolprovider",
            name="connection_method",
        ),
        migrations.AlterField(
            model_name="externaltoolprovider",
            name="launch_uri",
            field=models.URLField(
                blank=True,
                help_text="The launch (target link) URI for this external tool.This is the URL to launch the tool once the login process is complete.Sometimes this URL is called the 'redirection URI'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="externaltoolprovider",
            name="type",
            field=models.CharField(
                choices=[("BASIC_LTI13", "Basic LTIv1.3"), ("JUPYTER_HUB", "Jupyterhub"), ("RENKU", "Renku")],
                default="JUPYTER_HUB",
                max_length=50,
            ),
        ),
    ]
