# Generated by Django 5.0.6 on 2024-08-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_tools", "0003_alter_externaltoolprovider_launch_uri_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaltoolview",
            name="launch_type",
            field=models.CharField(
                choices=[("WINDOW", "window"), ("IFRAME", "iframe")], default="IFRAME", max_length=50
            ),
        ),
    ]
