# Generated by Django 5.1.1 on 2024-09-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_tools", "0004_alter_externaltoolview_launch_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaltoolview",
            name="append_to_default_launch_uri",
            field=models.BooleanField(
                default=False,
                help_text="If True, the 'Custom Launch URI' will be appended to the default launch URI to create a full URL.",
                verbose_name="Append custom launch URI to default launch URI",
            ),
        ),
        migrations.AddField(
            model_name="externaltoolview",
            name="custom_launch_uri",
            field=models.URLField(
                blank=True,
                help_text="A custom target link URI for this external tool view. If this URL is not defined, the default launch URI of the ExternalToolProvider will be used to launch the tool.",
                null=True,
                verbose_name="Custom Target Link URI",
            ),
        ),
    ]
