# Generated by Django 5.0.9 on 2024-10-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_tools", "0004_remove_externaltoolprovider_connection_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaltoolprovider",
            name="api_key",
            field=models.CharField(
                blank=True, help_text="The API key for the external tool.", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="externaltoolprovider",
            name="api_secret",
            field=models.CharField(
                blank=True, help_text="The API secret for the external tool.", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="externaltoolprovider",
            name="api_url",
            field=models.URLField(blank=True, help_text="The API endpoint for the external tool.", null=True),
        ),
    ]
