# Generated by Django 5.0.9 on 2024-10-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_tools", "0005_remove_externaltoolprovider_connection_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaltoolprovider",
            name="type",
            field=models.CharField(
                choices=[
                    ("BASIC_LTI13", "Basic LTIv1.3"),
                    ("MODAL_COM", "Modal.com"),
                    ("JUPYTER_HUB", "Jupyterhub"),
                    ("RENKU", "Renku"),
                ],
                default="JUPYTER_HUB",
                max_length=50,
            ),
        ),
    ]
