# Generated by Django 5.0.9 on 2024-10-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_tools", "0005_externaltoolprovider_api_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaltoolprovider",
            name="username_field",
            field=models.CharField(
                blank=True,
                choices=[("USERNAME", "username"), ("EMAIL", "email"), ("ANON_USERNAME", "anonymous username")],
                default="USERNAME",
                help_text="The field in the user model that will be used to identify the user to the tool",
                max_length=50,
                null=True,
            ),
        ),
    ]
