# Generated by Django 5.1.1 on 2024-09-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_tools", "0005_externaltoolview_append_to_default_launch_uri_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaltoolview",
            name="append_to_default_launch_uri",
            field=models.BooleanField(
                default=False,
                help_text="If True, the 'Custom Launch URI' will be appended to the default launch URI to create a full URL. If False, the 'Custom Launch URI' will be used as the full URL.",
                verbose_name="Append custom launch URI to default launch URI",
            ),
        ),
    ]
