# Generated by Django 5.1.1 on 2024-09-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_tools", "0006_alter_externaltoolview_append_to_default_launch_uri"),
    ]

    operations = [
        migrations.RenameField(
            model_name="externaltoolview",
            old_name="custom_launch_uri",
            new_name="custom_target_link_uri",
        ),
        migrations.AlterField(
            model_name="externaltoolview",
            name="append_to_default_launch_uri",
            field=models.BooleanField(
                default=False,
                help_text="If True, the 'Custom Target Link URI' will be appended to the default launch URI to create a full URL for the 'target_link_uri' sent to the tool when launched.If False, the 'Custom Target Link URI' will be used as the full URL in the 'target_link_uri'.",
                verbose_name="Append custom launch URI to default launch URI",
            ),
        ),
    ]
