# Generated by Django 5.1.1 on 2024-09-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_tools", "0007_rename_custom_launch_uri_externaltoolview_custom_target_link_uri_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaltoolview",
            name="custom_target_link_uri",
            field=models.URLField(
                blank=True,
                help_text="A custom target link URI for this external tool view. A custom target link helps direct to a particular resources in the external tool. If this URL is not defined, the default launch URI of the ExternalToolProvider will be used to launch the tool.",
                null=True,
                verbose_name="Custom Target Link URI",
            ),
        ),
    ]
