# Generated by Django 5.1.1 on 2024-09-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_tools", "0011_alter_externaltoolview_append_to_default_launch_uri"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externaltoolview",
            name="append_to_default_launch_uri",
        ),
        migrations.AddField(
            model_name="externaltoolprovider",
            name="default_target_link_uri",
            field=models.CharField(
                blank=True,
                help_text="The default target_link_uri sent as part of the tool launch. This value can be left empty. This value can also be overridden in Composer when a tool is added to a course unit.",
                max_length=1000,
                null=True,
                verbose_name="Default Target Link URI",
            ),
        ),
        migrations.AlterField(
            model_name="externaltoolview",
            name="custom_target_link_uri",
            field=models.CharField(
                blank=True,
                help_text="A custom target link helps direct to a particular resources in the external tool. If this URL is not defined, the default target_link_uri defined in the ExternalTool Provider is used.",
                max_length=1000,
                null=True,
                verbose_name="Custom Target Link URI",
            ),
        ),
    ]
