# Generated by Django 5.1.1 on 2024-09-19 00:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("external_tools", "0011_alter_externaltoolview_append_to_default_launch_uri"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externaltoolview",
            name="append_to_default_launch_uri",
        ),
    ]
