# Generated by Django 5.0.6 on 2024-08-05 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("survey", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="surveycompletion",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_completions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="surveyemail",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="survey_emails", to="survey.survey"
            ),
        ),
        migrations.AddField(
            model_name="surveyemail",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="survey_emails", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveys",
                to="survey.surveyprovider",
            ),
        ),
    ]
