# Generated by Django 5.0.9 on 2024-12-09 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_rename_course_home_content_course_course_home_html_content"),
        ("survey", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="course",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="surveys", to="course.course"),
        ),
    ]
