# Generated by Django 5.0.9 on 2024-12-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0003_alter_survey_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="slug",
            field=models.SlugField(blank=True, help_text="Slug identifier for survey (used in e.g. course json imports).", null=True, unique=True),
        ),
    ]
