# Generated by Django 5.0.6 on 2024-08-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeerComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("html_content", models.TextField(blank=True, null=True)),
                ("json_content", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomApp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(blank=True, max_length=400, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PEER_REVIEW_JOURNAL", "Peer review journal"),
                            ("COURSE_SPEAKERS", "Course Speakers"),
                            ("SIMPLE_HTML_CONTENT", "Html Content"),
                        ],
                        max_length=100,
                    ),
                ),
                ("slug", models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True)),
                ("short_description", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("tab_label", models.CharField(default="Custom", max_length=50)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_apps",
                        to="course.course",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AppItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        blank=True, choices=[("LONG_FORM_ENTRY_REVIEW", "long_form_entry_review")], max_length=100
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("html_content", models.TextField(blank=True, null=True)),
                ("json_content", models.JSONField(blank=True, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assessments.assessment",
                    ),
                ),
                (
                    "custom_app",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="custom_app.customapp",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomAppStudentSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("allow_public_view", models.BooleanField(default=False)),
                ("allow_user_view", models.BooleanField(default=False)),
                ("allow_user_comments", models.BooleanField(default=False)),
                ("allow_classmate_view", models.BooleanField(default=False)),
                ("allow_classmate_comments", models.BooleanField(default=False)),
                (
                    "custom_app",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_settings",
                        to="custom_app.customapp",
                    ),
                ),
            ],
        ),
    ]
