# Generated by Django 5.0.6 on 2024-08-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visible", models.BooleanField(default=True)),
                ("quote", models.TextField()),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the person giving the testimonial. This can be generic like 'student' or 'industry professional'",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="testimonials/")),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="course.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
    ]
