# Generated by Django 5.0.6 on 2024-08-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("course", "0001_initial"),
        ("learning_library", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="block",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="assessment", to="learning_library.block"
            ),
        ),
        migrations.AddField(
            model_name="submittedanswer",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="assessments.assessment"
            ),
        ),
        migrations.AddField(
            model_name="submittedanswer",
            name="course",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="course.course"
            ),
        ),
    ]
