# Generated by Django 5.0.6 on 2024-08-05 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="simpleinteractivetoolsubmission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simple_interactive_tool_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="simpleinteractivetooltemplate",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="The author of this template",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simple_interactive_tool_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="simpleinteractivetool",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="If defined, a template that describes the initial layout to be rendered when this SimpleInteractiveTool is first displayed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="simple_interactive_tools",
                to="sits.simpleinteractivetooltemplate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="simpleinteractivetoolsubmission",
            unique_together={("student", "simple_interactive_tool", "course")},
        ),
    ]
