# Generated by Django 5.0.6 on 2024-08-05 10:04

import kinesinlms.composer.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComposerSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "html_edit_mode",
                    models.CharField(
                        choices=[("RAW", "raw"), ("TINY_MCE", "tinymce")],
                        default="TINY_MCE",
                        help_text="Author edit mode for text fields.",
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EditStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("EDIT", "edit"), ("LOCKED", "locked")],
                        default=kinesinlms.composer.models.EditMode["LOCKED"],
                        max_length=30,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
