# Generated by Django 5.0.9 on 2024-12-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseImportTaskResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generation_status",
                    models.CharField(choices=[("PENDING", "Pending"), ("IN_PROGRESS", "In progress"), ("COMPLETED", "Completed"), ("FAILED", "Failed")], default="PENDING", max_length=50),
                ),
                ("import_file", models.FileField(blank=True, null=True, upload_to="course_imports")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
