# Generated by Django 5.0.9 on 2024-12-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0003_courseimporttaskresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseimporttaskresult",
            name="course_run",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="courseimporttaskresult",
            name="course_slug",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="courseimporttaskresult",
            name="create_forum_items",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="courseimporttaskresult",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
