# Generated by Django 5.0.9 on 2024-12-16 02:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0004_courseimporttaskresult_course_run_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="courseimporttaskresult",
            unique_together={("course_slug", "course_run")},
        ),
    ]
