# Generated by Django 5.0.9 on 2024-12-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0005_alter_courseimporttaskresult_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseimporttaskresult",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
