# Generated by Django 5.0.9 on 2024-12-16 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0006_courseimporttaskresult_error_message"),
        ("course", "0005_rename_course_home_content_course_course_home_html_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseimporttaskresult",
            name="course",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="import_tasks", to="course.course"),
        ),
    ]
