# Generated by Django 5.0.9 on 2024-12-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0007_courseimporttaskresult_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseimporttaskresult",
            name="percent_complete",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="courseimporttaskresult",
            name="status_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
