# Generated by Django 5.0.6 on 2024-08-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, help_text="Slug for institution", max_length=250, null=True)),
                (
                    "name",
                    models.CharField(blank=True, help_text="The name of this Institution", max_length=200, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
